name: Create release

on:
  push:
    branches:
      - main

jobs:
  print-head-ref:
    name: Print head ref
    runs-on: ubuntu-latest
    steps:
      - name: Print workflow trigger and inputs
        run: |
          echo "Workflow trigger: ${{ github.event_name }}"
          # Print any workflow inputs here if applicable

      - name: Print head ref and context
        run: |
          echo "${{ github.head_ref }}"
          echo "${{ github.ref }}"
          echo "${{ github.job }}"
          echo "${{ github.run_id }}"

  release:
    name: Release on merge to main
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'release/')
    steps:
      - name: Extract release tag
        id: extract_tag
        run: echo "tag=${GITHUB_HEAD_REF#release/}" >> $GITHUB_ENV

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          tag: ${{ env.tag }}
        run: |
          gh release create "v${tag}" \
              --repo="$GITHUB_REPOSITORY" \
              --title="v${tag}" \
              --generate-notes