name: debug-build

on:
  workflow_dispatch:
    inputs:
     release-version:
      description: Name of the release
      required: true
      type: string

jobs:
  debug-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Bump Version Code
        uses: chkfung/android-version-actions@v1.2.1
        with:
         gradlePath: app/build.gradle.kts
         versionCode: '${{ github.run_number }}'
         versionName: ${{ inputs.release-version }}

      - name: Setup Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: Build debug app
        run: ./gradlew assembleDebug

      - name: Upload app bundle as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: app/build/outputs/apk/debug/app-debug
            - run: 'echo Build status report=${{ job.status }}'
