name: Open pull request

on:
  workflow_dispatch:
    inputs:
      pr-title:
        description: Title of the pull request
        type: string
        required: true

jobs:
  open-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print branch name
        run: |
          echo ${{ github.ref_name }}

      - name: create pull request
        run: gh pr create -B ${{ github.ref_name }} -H main --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}